# Generated by Django 4.1.2 on 2023-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_solution_date_marked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
